#!/usr/bin/env ruby -wn

module Enumerable
  def mean
    sum / length
  end

  def sample_variance
    m = mean
    sum = sum(0.0) { |i| (i - m) ** 2 }
    sum / (length - 1)
  end

  def stddev
    Math.sqrt sample_variance
  end
end

FMT1 = "\rcount = %4d sum = %9.3f mean = %9.3f sd = %9.3f"
FMT2 = "%-5s = %9.3f"
FMT3 = "%-5s = %5d"

values = []

ARGF.each_line do |line|
  if line =~ /^\s*([-\d\.]+)/ then
    values << $1.to_f

    print FMT1 % [values.size, values.sum, values.mean, values.stddev]
  end
end

final = FMT1 % [values.size, values.sum, values.mean, values.stddev]

print "\r"
print " " * final.length
print "\r"
puts FMT2 % ["sum",   values.sum]
puts FMT3 % ["count", values.size]
puts FMT2 % ["mean",  values.mean]
puts FMT2 % ["sd",    values.stddev]
