#!/usr/local/bin/ruby -wns

# Adds the input and prints out the sum at the end

BEGIN {
  $total = 0.0
  $count = 0
}

if $_ =~ /^\s*([-\d\.]+)/ then
  $total += $1.to_f
  $count += 1
end

END {
  if defined? $m then
    puts $total / $count
  else
    puts $total
  end
}
