#!/usr/bin/perl -w

use strict;
use File::Basename;
use Getopt::Long;
use Date::Format;
use LWP::Simple;

my $symbol = 'AMZN';

my $today = time2str("%Y-%m-%d", time);
my $cmd = $0;
my $cmddir = dirname($cmd);
my $test = 0;

GetOptions('test' => \$test) || die "bad option";

# http://finance.yahoo.com/d/quotes.csv?s=AMZN&f=sl1d1t1c1ohgv&e=.csv
# s  = ticker symbol
# l1 = last price
# d1 = date
# t1 = time
# c1 = change
# o  = open price
# h  = daily high
# g  = daily low
# v  = volume

my $price = shift || 0;
my $change;

unless ($price) {
  my $fields = 'l1c1';
  my $data = get "http://quote.yahoo.com/d/quotes.csv?s=$symbol&f=$fields&e=.csv";
  die unless $data;

  ($price,$change) = split(/,/, $data);
}

my $value = 0;
while (<DATA>) {
  next if m/^\s*\#/;
  if (/^\s*(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s*/) {
    my ($type, $count, $date, $strike) = ($1, $2, $3, $4);

    if ($today ge $date) {
      $value += ($count * ($price - $strike));
    }
  }
}

my $message = sprintf("%s \$%.2f (\$%+.2f) total=\$%d", 
		      $symbol, $price, $change, $value);

if ($test) {
  print "$message\n";
} else {
  $message =~ s/\$/\\\$/g;
  print `$cmddir/pageryand "$message"`;
}

__DATA__

#type	count	vestdate	strike$

ISO	6600	1999-09-01	12.6354
ISO	-6600	1999-09-01	12.6354
ISO	6600	2000-09-01	12.6354
ISO	6600	2001-09-01	12.6354
ISO	6600	2002-09-01	12.6354
ISO	6600	2003-09-01	12.6354

NQ	200	2001-08-14	13.3750
NQ	600	2003-02-14	13.3750


NQ	360	2002-09-06	7.9300
NQ	360	2003-09-06	7.9300
NQ	360	2004-09-06	7.9300
NQ	360	2005-09-06	7.9300
NQ	360	2006-09-06	7.9300

NQ	2160	2006-07-01	7.9300
