#!/usr/bin/perl -w

use strict;

############################################################
my $strike = 75.5 / 3;
my $amount = 5500 * 3;
my $symbol = 'AMZN';
############################################################

use File::Basename;
my $cmd = $0;
my $cmddir = dirname($cmd);

use LWP::Simple;
my $price = get "http://quote.yahoo.com/d/quotes.csv?s=$symbol&f=l1&e=.csv";
die unless $price;

$price =~ s/\s*(\S+)\s*/$1/s;
my $options = int($amount * ($price - $strike));
my $subject = sprintf("A %6.2f%8d", $price, $options);

print `$cmddir/pageryand $subject`;
