#! /bin/bash
    
for dir in "${@%/}" ; do
  if [ ! -d "$dir" ]; then
    echo "Error: $dir is not a directory"
  else
    tar c "$dir" | zstdmt -7 --long > "$dir.tar.zst" && rm -rf "$dir"
  fi
done

