#!/usr/bin/env ruby -wn

module Enumerable
  def mean
    sum / length
  end

  def sample_variance
    m = mean
    sum = sum(0.0) { |i| (i - m) ** 2 }
    sum / (length - 1)
  end

  def standard_deviation
    Math.sqrt sample_variance
  end
end

FMT = "\rsum = %7.4f mean = %7.4f sd = %7.4f"
FMT2 = "%-4s = %10.6f"

values = []

ARGF.each_line do |line|
  if line =~ /^\s*([-\d\.]+)/ then
    values << $1.to_f

    print FMT % [values.sum, values.mean, values.standard_deviation]
  end
end

print "\r"
print " " * 50
print "\r"
puts FMT2 % ["sum",  values.sum]
puts FMT2 % ["mean", values.mean]
puts FMT2 % ["sd",   values.standard_deviation]
