#!/usr/bin/bash

exec 2>&1

M=zap:gharlane:clarkie:denim:dad:t-server:crom:lily:Shark:mom:spandex:rock:oboe:speedy:space:oddjob:bird:wyeast:brando:hope:mozart:obiwan:hobbit:sparky:puccini:classy:faraway:silk:sackbut:hotrod:frog:glass:glasseye:backup:slcyp1:lucky:ship:netman:duke:emerald:aok:handel:holmes:servio:slcgate:bach:ludwig:vroom:www:trout:ella:hoopster:yoda:warp:topdog:bud:kroozer:zoomer:thunder:krystal:slammer:chinook:knight:thor:daisy:britten:leko:mayo:klaatu:bigtoy:worsel:tahoma:trail:blazer:ncr:achtung:autobahn:ducky:

IFS=:
com=${0##*/}			# save command name

# Do all file processing here:
for m in $M; do		# process multiple files

  echo -n "$(suntype $m):$m:"
  rsh $m 'echo ${BASH_VERSION}'

done

