#!/usr/bin/bash

#set -xv

cd /home/ryand
mkdir bugbash.data &> /dev/null
cd bugbash.data && rm -rf ELM*

PATH=$PATH:/var/ddts/bin

for bug in $(findbug -NOA) ; do
  dumpbug -fR $bug > $bug
done

#date | mailx -s "Done rebuilding bugbash files" ryand
