#!/bin/csh
# by RWD modified 11-12-93
# checklink is a setup program that should be added to .login. It allows for
# the creation of directories and  links to them...
#
# Usage:
# 	checklink sourcedir destlink

### Setup for temp directory

set progname = $0:t			# save command name

if ($#argv < 2) then		# check num of arguments
	echo $progname": creates directories if non-existant."
	echo "Usage: $progname <dir> <link>"
	exit 1
endif

# Do all file processing here:
set dir = $argv[1]

if (! -e $dir ) then
	mkdir $dir
	echo "NOTE: $dir directory was recreated."
endif

shift				# remove the directory entry

# Do all file processing here:
foreach lnk ($argv)		# process multiple files

if (! -e $lnk ) then
	ln -s $dir $lnk
	echo "NOTE: $lnk link was recreated."
endif

end
