#!/bin/bash

for dir in MyApplications Applications/MyApplications Applications; do
    bin=/$dir/Emacs.app/Contents/MacOS/Emacs
    if [ -x $bin ]; then
        exec $bin "$@"
    fi
done

echo "Couldn't find an emacs GUI to run"
exit 1
