#!/usr/bin/bash

#set -xv

com=${0##/*/}			# save command name

usage() {

  echo "Usage: $com {-n} {-I ignoreFiles} {-r repository} {files}"
}

while getopts "nI:r:" opt; do

  case $opt in

    n)
      N="-n";;
    I)
      IGNORE="-I $OPTARG";;
    *)
      usage
      echo "$com error: unknown option $opt"
      exit 1;;
    
  esac
  
done
shift $(($OPTIND - 1))
  
cvs ${N-} update ${IGNORE-} $* 2>&1 | /bin/egrep -v "^cvs update: Updating"

