#!/usr/local/bin/bash -noprofile

set -xv

com=${0##/*/}			# save command name

usage() {

  echo "Usage: $com {-n} {-I ignoreFiles} {-r repository} {files}"
}

while getopts "nI:r:" opt; do

  case $opt in

    n)
      N="-n";;
    I)
      IGNORE="-I $OPTARG";;
    r) 
      ROOT=$OPTARG;;
    *)
      usage
      echo "$com error: unknown option $opt"
      exit 1;;
    
  esac
  
done
shift $(($OPTIND - 1))
  
# export CVSROOT=${ROOT-/src/cvs}

cvs ${N-} update ${IGNORE-} $* 2>&1 | grep -Ev "^cvs (update|server): Updating"
