#!/usr/bin/env ruby -w

Dir.chdir(File.expand_path("~/Downloads")) do
  system "ruby sync.rb push"
  unless ARGV.empty? then
    urls = ARGV
    cmd = ["ssh", "g", "aria2c", "-d", "Downloads", "--seed-time", "0", *urls]
    system(*cmd)
    system "ruby sync.rb pull"
  end
end
