#!/usr/bin/ruby

Dir.chdir(File.expand_path("~/Downloads")) do
  system "ruby sync.rb push"
  unless ARGV.empty? then
    urls = ARGV.map { |url| "\\\"#{url}\\\"" }
    system "ssh e \"sh -vxc 'cd ~/Downloads && aria2c --seed-time=0 #{urls.join " "}'\""
    system "ruby sync.rb pull"
  end
end
