#!/bin/env perl

require 5.002;
use strict;

use LWP::Simple;
use URI::Heuristic qw(uf_urlstr);

foreach (@ARGV) {
  my $url = uf_urlstr($_);
  print "=" x 60, "\n$url\n";
  getprint($url);
}
print "=" x 60, "\n";
