#!/usr/local/bin/bash

JDK_DOCS=${2:-/mom2/users/ryand/snapshots.10J/fast10/doc/api}
RESULTS=/tmp/results.html

#if [ $# -eq 0 ]
#then
#	echo Usage: jdkgrep \"pattern\" [directory]
#	echo
#	echo Searches the JDK\'s Docs directory for .html files
#	echo that contains the \"pattern\" and puts links to
#	echo matching files in the file tmp/results.html.
#	echo
#	exit 1
#fi
#
#cat > ${RESULTS} <<EOF
#<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
#<HTML>
#  <HEAD>
#    <TITLE>JDK Search Results</TITLE>
#  </HEAD>
#
#  <BODY>
#
#    <H1>Search results for $1</H1>
#    <UL>
#
#EOF

fgrep -l -i $1 $(find $JDK_DOCS -name \*.html -print)
# perl5 -pe 'use File::Basename; s|^(.+)$|      <LI><A HREF=\"file://$1\">|; $_ .= basename($1) . "</A>\nA"' >> ${RESULTS}

#cat >> ${RESULTS} << EOF
#    </UL>
#    <HR>
#    <ADDRESS><A HREF="mailto:ryand@gemstone.com">Ryan Davis</A></ADDRESS>
#  </BODY>
#</HTML>
#EOF