#!/bin/csh
# script to process text files with long lines

if ($#argv == 0) then			# no files given as argument,
	awk "length > 80"		# so process standard input.
	exit 0
endif

foreach File ($argv)			# process multiple files

if (-f $File) then			# check to see if plain file
	echo $File\:			# display file name
	pr -e4 -o4 $File | awk "length > 80"
else
	echo $0\ No file $File		# print error message
	exit 1				# exit abnormally
endif

end
