#!/usr/bin/perl -w

use strict;

use File::Find;

@ARGV = ('.') unless @ARGV;

my @files = ();
find(\&wanted, @ARGV);
&show;

sub wanted {
  push @files, $File::Find::name if -f;
}

sub show {
  @files = sort {(stat($a))[9] <=> (stat($b))[9]} @files;

  print join("\n", @files, '');
}
