#!/usr/local/bin/ruby

require 'fileutils'

date = Time.now.strftime("%Y-%m")

mailboxen = %w(
            Personal/Amy
	    Personal/General
	    Personal/Bryan
	    Personal/Family
	    Personal/Phil
	    Technical/Ruby
	    ).map { |base| "#{base}.#{date}" }

Dir.chdir(File.expand_path("~/Mail"))
FileUtils.touch mailboxen

