#!/opt/third-party/bin/perl -w
use strict;

print "Initializing...\n";

my $clear = `clear`;
my $i = 0;

my $homedir = (getpwnam('ryand'))[7];
my $maildir = "$homedir/Mail/spool";
chdir($maildir) || die "Couldn't cd to '$maildir': $!";
opendir(DIR, '.');
my @dirs = grep { /^[^\.]/ } readdir(DIR);
closedir(DIR);

while (1) {
  my %count = ();
  my $mail;

  for $mail (@dirs) {
    
    open(MAIL, $mail) 
      or warn "Can't open $mail: $!\n\t";
    while (<MAIL>) {
      $count{$mail}++ if /^From: /i;
    }
  }
  
  print $clear;
  print $i++, ": ";
  if (%count) {
    my $key;
    for $key (sort keys %count) {
      print "$key($count{$key}) ";
    }
    print "\n";
  } else {
    print "none\n";
  }
  my $time = 60;
  sleep($time);
}

exit 0;
