#!/bin/csh

set com = $0			# save command name

if ($#argv < 1) then		# check num of arguments
	super mount -o ro -v cdrfs /dev/cd0 /cdrom
else
	if ($argv[1] == "-u") then
		super umount /cdrom
	else
		echo "Unknown command: $*"
	endif
endif


