#!/usr/local/bin/ruby -w

t = Time.now

mday = t.day

cmon  = t.month; nmon  = cmon + 1; pmon = cmon - 1
cyear = t.year;  nyear = cyear;   pyear = cyear
if nmon == 13 then nmon =  1; nyear += 1; end
if pmon ==  0 then pmon = 12; pyear -= 1; end

prv = `cal #{pmon} #{pyear}`.split(/\n/)
cur = `cal #{t.month} #{pyear}`.split(/\n/)
nxt = `cal #{nmon} #{nyear}`.split(/\n/)

max = [prv, cur, nxt].map{|a| a.size}.max
merged = ([nil] * max).zip(prv, cur, nxt)

merged.each do |lines|
  x, a, b, c = *lines
  b = " #{b} " # to ensure regex matches
  b.sub!(/\s#{mday}\s/, "*#{mday}*") unless b.nil?
  printf("%-20s |%-22s| %-20s\n", a, b, c)
end
