#!/usr/bin/env ruby -w

require 'net/http'

text =
  if ARGV.empty? then
    $stdin.tty? ? `pbpaste` : $stdin.read
  else
    File.read(ARGV.shift)
  end

uri = URI.parse 'http://paste.segment7.net/'

res = Net::HTTP.post_form uri, :text => text
location = res['location']

IO.popen 'pbcopy', 'w' do |io| io.write location end

puts location

