#!/usr/bin/env ruby -w

require "rbconfig"

begin
  ARGF.each_line do |line|
    puts line.gsub(/#{Dir.pwd}/o, ".").
      gsub(/#{RbConfig::CONFIG["rubylibdir"]}/o, "RUBYLIB").
      gsub(/#{RbConfig::CONFIG["sitedir"]}/o, "RUBYSITE").
      gsub(/#{Gem.dir}.gems/o, "GEMS")
  end
rescue Exception
  warn ""
  warn "Interrupted... done"
  abort "done"
  exit(74)
end
