#!/usr/bin/env ruby -ws

$r ||= false
$h ||= false

class Array
  def human_sort
    regexp = $h ? /(\h+)/ : /(\d+)/
    base   = $h ? 16      : 10
    sort_by { |item| item.to_s.split(regexp).map { |e| [e.to_i(base), e] } }
  end
end

res = ARGF.readlines.human_sort
res = res.reverse if $r
puts res
