#!/usr/bin/env ruby -ws

$r ||= false
$h ||= false

class Array
  def human_sort
    base = $h ? 16 : 10
    sort_by { |item| item.to_s.split(/(\d+)/).map { |e| [e.to_i(base), e] } }
  end
end

res = ARGF.readlines.human_sort
res = res.reverse if $r
puts res
