#!/usr/bin/env -S ruby -ws

$b ||= false
$B ||= false
$c ||= false
$g ||= false
$h ||= false
$I ||= false
$i ||= false
$l ||= false
$n ||= false
$o ||= false
$p ||= $c
$w ||= false
$s ||= false
$t ||= false
$x ||= false

if $h then
  puts "#{File.basename($0)} [options] [files]"
  puts "  -h - show help"
  puts "  -B - force input encoding to binary"
  puts "  -o - skip lines that only occur once"
  puts "  -s - sort by line, rather than occurrence"
  puts
  puts "  -I - ignore case"
  puts "  -b - strip leading and trailing whitespace, and blanks"
  puts "  -t - format with tabs so it is pastable into a spreadsheet"
  puts "  -w - preserve whitespace as-is"
  puts
  puts "  -i - strip ip numbers"
  puts "  -n - convert numbers to '<num>'"
  puts "  -x - convert hex numbers to '0x<num>'"
  puts
  puts "  -c - cumulative percentages"
  puts "  -p - add percentage values to the output"
  puts
  puts "  -g - print a simple histogram"
  puts "  -l - print the histogram logarithmically"

  exit 0
end

c = Hash.new 0
total = 0

ARGF.set_encoding("binary") if $B

ARGF.each_line do |line|
  line = line.chomp
  line.gsub!(/\c[\[\d+m/, '')
  line.gsub!(/0x(\d|[a-f])+/i, '0x<num>') if $x

  # regex is split this way so you get all dots or dashes, not a mix
  line.gsub!(/(\d+((\.\d+)*|(\-\d+)*))/) do |match|
    if match.split(/[\.-]/).size >= 4 then # IP number
      if $i then
        "<ip>"
      else
        match
      end
    else
      "<num>"
    end
  end if $n

  line.gsub!(/<num>x<num>/, '0x<num>') if $x

  line.gsub!(/\s{2,}/, ' ') unless $w

  if $b then
    line.strip!
    next if line.empty?
  end

  line.downcase! if $I
  c[line] += 1
  total += 1
end rescue nil # silence broken pipe errors

if $s then
  sorted = c.keys.sort
else
  sorted = c.keys.sort { |a,b| c[b] <=> c[a] }
end

total = total.to_f

if $g then
  max_s = c.keys.map { |s| s.size }.max
end

curr = 0.0

mag = c[c.keys.max_by { |k| c[k] }].to_s.size

sorted.each do |key|
  next if $o and c[key] == 1
  if $c then
    curr += c[key]
    cul = curr / total * 100.0
    pct = c[key] / total * 100.0
    printf "%#{mag}d:%5.2f%%:%5.2f%%:%s\n", c[key], pct, cul, key
  elsif $p then
    printf "%#{mag}d:%5.2f%%:%s\n", c[key], c[key] / total * 100.0, key
  elsif $t then
    printf "%s\t%#{mag}d\n", key, c[key]
  elsif $g then
    n = c[key]
    n = Math.log(n) if $l
    printf "%*s: %s\n", max_s, key, "x" * n
  else
    printf "%#{mag}d:%s\n", c[key], key
  end
end rescue nil # silence broken pipe errors
