#!/usr/bin/perl -w

use strict;
use Getopt::Long;

my %option = ();
GetOptions(\%option,
           "n",
	   "b|w",
	   "o",
           );

my %c = ();

while (<>) {
  chomp;

  s/(\d+)/<num>/g if $option{n};

  if ($option{b}) {
      s/^\s+//g;
      s/\s+$//g;
      next unless $_;
  }

  $c{$_}++;
}

foreach my $key (sort { $c{$b} <=> $c{$a} } keys %c) {
  next if $option{o} and $c{$key} == 1;
  printf "%5d: %s\n", $c{$key}, $key;
}
