#!/usr/bin/bash

#set -vx

com=${0##*/}

#Icky, needed to get date to print the format of today minus 1 month.
#So, I had to get this month, subtract 1, and then pass that
#back to date to get this day and the rest of the format.
year=$(date +%y)
lastmonth=$(($(date +%m) - 1))
if [ $(( $lastmonth <= 0 )) ]; then
  lastmonth=12;
  year=$(($year-1))
fi

old=$(date +$lastmonth%d0000$year)

age=/tmp/$com.$$
touch $old $age

for dir in /$(hostname)*/users/*; do
  if [ $dir -ot $age ]; then

    case "${machine}" in
      "5" )
	    du -s $dir;;
      "7" ) 
	    du -s $dir;;
      * )
	  du -sk $dir;;
    esac

  fi
done

command rm $age
