#!/usr/bin/ruby

name = `hostname -s`.chomp

if name == "YPCMC09457" then
  name = "lust"
  warn "atti sucks, renaming machine to #{name}"
end

extra = ARGV.dup
base = dirs = nil

case name
when "lust" then
  dirs = %w(Documents Work)
  base = File.expand_path "~"
when "envy" then
  dirs = %w(perforce www blogs)
  base = "/Volumes/Users"
else
  abort "unknown machine #{name}"
end

Dir.chdir base

flags  = "-aCz"
flags += "vP" if $stdin.tty? and $stdout.tty?

cmd = ["rsync", flags, "--del", extra,
       "--exclude", "tmp",
       "--exclude", "pkg",
       "--exclude", "*.build",
       "--exclude", "\*.ofocus-backup",
       dirs,
       "rsync:backups/#{name}"].flatten

puts "starting rsync backup"
p cmd
system(*cmd)
puts "finished rsync backup"
