#!/usr/bin/env ruby -w

require "shellwords"

name = `hostname -s`.chomp

extra = ARGV.dup
base = dirs = nil

flags  = ["-aCz"]
flags << "-vP" if $stdin.tty? and $stdout.tty?

case name
when "wrath" then
  dirs = %w(Documents Work)
  base = File.expand_path "~"
when "greed" then
  dirs = %w(perforce www)
  base = "/Users"
else
  abort "unknown machine #{name}"
end

Dir.chdir base

args = %W[find  ( -name .DS_Store -o -name *~ ) -print -delete]
args[1,0] = dirs
cmd = args.shelljoin

puts cmd
system cmd

del = if extra.grep(/del/).empty? then
        "--del"
      else
        nil
      end

cmd = ["rsync", flags, del, extra,
       "--include", ".git",
       "--include", ".svn",

       "--delete-excluded",

       "--exclude", "tmp",
       "--exclude", ".DS_Store",
       "--exclude", "*~",
       "--exclude", "pkg",
       "--exclude", ".ext",
       "--exclude", "*.build",
       "--exclude", "backups",
       "--exclude", "compiled",
       "--exclude", "unreadable*",
       "--exclude", "*.dbf", # maglev files
       "--exclude", "gauntlet\*.noindex\*",
       "--exclude", "\*.ofocus-backup",
       "--exclude", "Keychains",
       "--exclude", "com.apple.LaunchServices",
       dirs,
       "rsync:backups/#{name}"].flatten.compact

warn cmd.join " "
system(*cmd)
