#!/usr/bin/env ruby -w

require "shellwords"

name = `hostname -s`.chomp.downcase

extra = ARGV.dup
base = dirs = nil

flags  = ["-aCz"]
flags << "-vP" if $stdin.tty? and $stdout.tty?

case name
when "wrath", "envy" then
  dirs = %w(Documents Work)
  base = File.expand_path "~"
when "greed" then
  dirs = %w(perforce www)
  base = "/Users"
else
  abort "unknown machine #{name}"
end

Dir.chdir base

cmd = %W[ fd -Htf .DS_Store|~$ -x rm -v ]
cmd[3,0] = dirs
puts cmd.shelljoin
system(*cmd)

del = if extra.grep(/del/).empty? then
        "--del"
      else
        nil
      end

includes = %w[
              .git
              .svn
             ]

excludes = %w[
              *.build
              *.dbf
              *~
              .DS_Store
              .ext
              Keychains
              *.ofocus-backup
              backups
              com.apple.LaunchServices
              compiled
              gauntlet*.noindex*
              pkg
              ruby-*.tar.xz
              tmp
              unreadable*
              zig-cache
              zig-out
             ]

cmd = ["/opt/homebrew/bin/rsync", flags, del, extra,
       "--log-file", "/tmp/rsync_backup.log",

       includes.map { |pat| ["--include", pat] },

       "--delete-excluded",

       excludes.map { |pat| ["--exclude", pat] },

       dirs,
       "rsync:backups/#{name}"
      ].flatten.compact

puts cmd.shelljoin
system(*cmd)
