#!/usr/bin/ruby -w

version = ARGV.shift || "X.Y.Z"
date    = ARGV.shift || "YYYY-MM-DD"
date    = Time.now.strftime("%Y-%m-%d") if date == "today"

$changes = Hash.new { |h,k| h[k] = [] }

codes = {
  "!" => :major,
  "+" => :minor,
  "*" => :minor,
  "-" => :bug,
}

ARGF.each do |line|
  case line
  when /^\t\s*([#{Regexp.escape codes.keys.join}])\s*(.*)/ then
    code, line = codes[$1], $2
    $changes[code] << line
  end
end

def section code
  name = {
    :major => "major enhancement",
    :minor => "minor enhancement",
    :bug   => "bug fix",
  }[code]

  changes = $changes[code]
  count = changes.size
  name += "s" if count > 1
  name.sub!(/fixs/, 'fixes')

  return if count < 1

  puts "* #{count} #{name}:"
  puts
  changes.sort.each do |line|
    puts "  * #{line}"
  end
  puts
end

puts "== #{version} / #{date}"
puts
section :major
section :minor
section :bug
