#!/usr/bin/perl -w

use strict;
use Mail::Mailer;

my $msg = join(' ', @ARGV) || die "need a message to page with";

my $mail = Mail::Mailer->new();
$mail->open({
	     To      => 'ryand-pager@zenspider.com',
	    })
  or die "Can't open mail: $!\n";
print $mail $msg;
$mail->close();

print "Sent '$msg'\n";
