#!/usr/bin/perl -w

use strict;
use Mail::Mailer;

my $msg = join(' ', @ARGV) || 'Call me 206.266.2641';

my $mail = Mail::Mailer->new();
$mail->open({
	     To      => '7938204@skytel.com',
	     Subject => $msg,
	    })
  or die "Can't open mail: $!\n";
print $mail '';
$mail->close();

print "Sent '$msg'\n";
