#!/bin/sh -- # -*- perl -*-
eval 'exec perl -w -S $0 ${1+"$@"}'
  if 0;

use strict;
use Mail::Mailer;

my $mail = Mail::Mailer->new();
$mail->open(
	    {
	      From    => 'ryand@amazon.com',
	      To      => '1139930@skytel.com',
	      Subject => 'Call me 206.694.2641',
	    }
	    )
  or die "Can't open mail: $!\n";
print $mail "call me\n";
$mail->close();
