#!/usr/bin/perl -w

use strict;
use Mail::Mailer;

my $msg = join(' ', @ARGV) || die "need a message to page with";

my $mail = Mail::Mailer->new();
$mail->open({
	     To      => 'ryan.davis@voicestream.net',
	     Subject => $msg,
	    })
  or die "Can't open mail: $!\n";
print $mail '';
$mail->close();

print "Sent '$msg'\n";
