#!/usr/bin/env -S ruby -ws

$q ||= false
$d ||= false

require "date"
require "fileutils"

# backup_dates - returns a list of dates of backups to keep
#
# 28   days of dailies          1 month
#  2 months of weeklies         3 months
#  9 months of monthlies       12 months / 1 year
#  9  years of yearlies        10 years

def backup_dates offset=0
  today   = Date.today + offset

  daily   = (today-27..today).to_a
  d_min   = daily.min

  weekly  = (d_min-7*9...d_min)
    .select { |d| d.day < 28 && d.day % 7 == 1 }
    .last 8
  w_min   = weekly.min

  monthly = (w_min-366...w_min)
    .select { |d| d.day == 1 }
    .last 9
  m_min   = monthly.min

  yearly  = (m_min-365.246*10...m_min)
    .select { |d| d.yday == 1 }
    .last 9

  [ yearly, monthly, weekly, daily ]
end

y, m, w, d = backup_dates
keep = [y, m, w, d].flatten

if ARGV.empty? then
  puts "Yearly: (%d)" % [y.size]
  puts y.each_slice(3).map { |a| a.join(" ") }
  puts
  puts "Monthly: (%d)" % [m.size]
  puts m.each_slice(3).map { |a| a.join(" ") }
  puts
  puts "Weekly: (%d)" % [w.size]
  puts w.each_slice(4).map { |a| a.join(" ") }
  puts
  puts "Daily: (%d)" % [d.size]
  puts d.each_slice(7).map { |a| a.join(" ") }
else
  all = Dir[*ARGV].
    sort_by { |f| -File.mtime(f).to_f }.
    map { |f| [f, File.mtime(f).to_date] }.
    to_h

  good = keep.map { |t0| all.values.min_by { |t1| (t0 - t1).abs } }.uniq
  bad  = all.select { |_, t| not good.include? t }

  if $d then
    bad = bad.map(&:first)

    bad_files, bad_dirs = bad.partition { |f| File.file? f }

    deleted = File.unlink(*bad_files)

    puts "Deleted #{deleted} files" unless deleted.zero? unless $q

    FileUtils.rm_r bad_dirs

    puts "Deleted #{bad_dirs.size} directories" unless $q
  else
    puts "Deleted #{bad.size} files (no-op)"
    puts
    puts bad.keys.sort
  end
end
