#!/usr/bin/perl -w

use strict;
use IO::File;

$| = 1;

my $max = shift || 5;
my $args = join(' ', @ARGV) || '';
my @f;


for (my $i = 0; $i < $max; ++$i) {
  my $fh = new IO::File "| xargs $args";
  die "Couldn't create pipe #$i: $!" unless defined $fh;
  push @f, $fh;
}

my $i = 0;
while (<STDIN>) {
  my $fh = $f[$i++ % $max];
  print $fh $_;
}
