#!/usr/bin/perl -w

use strict;
use Socket;

my $number = shift || do {
  print "You must supply an ip #\n";
  exit 1;
};

if ($number =~ m/(\d+\.\d+\.\d+)\.\d+/) {
  my $base = $1;

  foreach my $n (1..254) {
    print lookup_host("$base.$n"), "\n";
  }

} else {
  print "You must supply an ip # like 1.2.3.4\n";
  exit 1;
}

sub lookup_host {
  my ($host) = @_;

  my $pretty_ip = sprintf("%03d.%03d.%03d.%03d", split(/\./, $host));
  my $url = gethostbyaddr(inet_aton($host), AF_INET)
    || 'unable to resolve';
  
  return ("$pretty_ip $url");
}
