#!/usr/bin/ruby -w

require 'find'

ctags = Dir["/{opt,usr}/local/bin/ctags"].first
langs = "Ruby,Lisp,YACC,C,C++,Scheme"
excls = ".git|.svn|vendor|db"
cmd   = "#{ctags} -Re --languages=#{langs} --exclude='#{excls}' ."

ARGV.unshift '.' if ARGV.empty?

ARGV.each do |dir|
  Dir.chdir dir do
    newest = Dir["**/*"].map { |f| File.mtime(f) if File.file?(f) }.compact.max
    tags   = File.exist?("TAGS") ? File.mtime("TAGS") : Time.at(0)

    if newest > tags then
      warn "retagging #{dir}"
      File.unlink "TAGS" if File.file?("TAGS")
      system cmd
    end
  end
end
