#!/usr/bin/ruby -w

require 'find'

ctags = Dir["/{opt,usr}/local/bin/ctags"].first

abort "Can't find ctags" unless ctags

langs = "Ruby,Lisp,YACC,C,C++,Scheme"
excls = ".git|.svn|vendor|tmp|db|gauntlet*"
cmd   = "#{ctags} -Re --languages=#{langs}"

cmd << " --langmap=Scheme:+.rkt"

excls.split(/\|/).each do |excl|
  cmd << " --exclude='#{excl}'"
end

puts cmd

ARGV.unshift '.' if ARGV.empty?

ARGV.each do |dir|
  Dir.chdir dir do
    newest = Dir["**/*"].map { |f| File.mtime(f) if File.file?(f) }.compact.max
    tags   = File.exist?("TAGS") ? File.mtime("TAGS") : Time.at(0)

    if newest > tags then
      warn "retagging #{dir}"
      File.unlink "TAGS" if File.file?("TAGS")
      system "#{cmd} #{dir}"
    end
  end
end
