#!/usr/bin/ruby -ws

$n ||= false

require "csv"
require "time"

min = Time.now - (3*86_400)

system "t set active seattlerb"

csv = `t mentions --csv | cut -f1-3 -d, | grep ,pete_higgins`

mentions = CSV.parse csv

mentions.map!    { |id, date, _| [id, Time.parse(date)] }
mentions.select! { |_, date, _| date > min }

puts "Retweeting:"
puts
mentions.reverse_each do |id, date|
  puts `t status #{id} | grep ^Text`
  puts
end

system "t retweet #{mentions.map(&:first).reverse.join " "}" unless $n

system "t set active the_zenspider"
