#!/bin/bash

FLAGS="-NAXx --fileflags --force-change --protect-decmpfs --protect-args"
EXCLS=".DS_Store .fseventsd .Trashes .Spotlight-V100 .com.apple.timemachine\* .DocumentRevisions-V100 .TemporaryItems"

FLAGS="${FLAGS}$(printf " --exclude %s" $EXCLS)"

exec rsync $FLAGS "$@"
