#!/bin/bash

FLAGS="-NAXxs --fileflags --force-change"
EXCLS=".DS_Store .fseventsd .Trashes .Spotlight-V100 .com.apple.timemachine\* .DocumentRevisions-V100 .TemporaryItems"

FLAGS="${FLAGS}$(printf " --exclude %s" $EXCLS)"

exec rsync $FLAGS "$@"
