#!/usr/bin/env ruby -w

command = ARGV.shift
files = {}

ARGV.each do |arg|
  arg = "#{arg}/**/*.rb" if File.directory? arg
  Dir[arg].each { |file|
    files[file] = Time.at 0
  }
end

puts "Files: #{files.keys.length}"

trap('INT') do
  puts "\nQuitting..."
  exit
end

loop do
  sleep 1

  newest = files.keys.max_by { |f| File.mtime(f) }

  latest_change = File.mtime newest

  if latest_change > files.values.max then
    files.keys.each do |f|
      files[f] = latest_change
    end

    puts "=> Detected a change in #{newest}"
    puts "   Running: #{command}"

    results = `#{command}`
    puts results
  end
end
