#!/usr/local/bin/ruby -ws

raise "need a revision to describe" if ARGV.empty?

url = $1 if `svn info | grep URL` =~ /(http.*)/
puts "url = #{url}"

args = ARGV.map { |arg|
  case arg
  when /^\d+$/ then
    arg
  when /^review$/ then
    first = `svnversion . | cut -f1 -d:`.gsub(/\D+/, '')
    last = `svn info #{url} | grep Revision:`.gsub(/\D+/, '')
    warn "Reviewing #{first} to #{last}"
    ((first.chomp.to_i)..(last.chomp.to_i)).to_a
  when /(\d+)\.\.(\d+|head)/i then
    first = $1.to_i
    last = if $2 == "head" then
             `svn -u st -N | tail -1`.gsub(/\D+/, '').to_i
           else
             $2.to_i
           end
    warn "Reviewing #{first} to #{last}"
    (first..last).to_a
  else
    raise "unknown arg: #{arg}"
  end
}.flatten

args.each do |rev|
  $stderr.puts "Revision = #{rev}"

  prev = rev.to_i - 1

  files = Hash.new { |h,k| h[k] = [] }
  desc = []
  in_files = false
  
  puts
  puts `svn log -v -r#{rev} #{url}`.gsub(/\r/, '')
  unless defined? $q then
    puts
    puts `svn diff -r#{prev}:#{rev} #{url}`.gsub(/\r/, '')
  end
end
