#!/bin/bash

for arch in "$@" ; do
    file=$(basename $arch)
    ext=${file##*.}

    case $ext in
        "zst" )
            zstd -dc "$arch" | tar x && rm -f "$arch"
            ;;
        "lrztar" )
            lrzuntar "$arch" && rm -f "$arch"
            ;;
    esac
    # 
done

