#!/usr/bin/env ruby -w

require "open-uri"
require "net/http" # avoid require issues in threads
require "net/https"

cpus = `sysctl -n hw.logicalcpu`.to_i

base_url = "https://cache.ruby-lang.org/pub/ruby"

versions = ("2.3".."2.7").to_a

class Array
  def human_sort
    sort_by { |item| item.to_s.split(/(\d+)/).map { |e| [e.to_i, e] } }
  end
end

versions = versions.map { |ver|
  Thread.new {
    URI
      .parse("#{base_url}/#{ver}/")
      .read
      .scan(/ruby-\d+\.\d+\.\d+[-\w.]*?.tar.gz/)
      .human_sort
      .last
      .delete_prefix("ruby-")
      .delete_suffix ".tar.gz"
  }
}.map(&:value).sort

rubies = File.expand_path "~/.rubies"
Dir.mkdir rubies unless File.directory? rubies

old_versions = Dir.chdir rubies do
  Dir["ruby-*"].map { |s| s.delete_prefix "ruby-" }.sort
end

good    = versions & old_versions
install = versions - old_versions
delete  = old_versions - versions

# https://github.com/postmodern/ruby-install/issues/363#issuecomment-580699347
extra = {
  "2.3.8" => "--with-openssl-dir=$(brew --prefix openssl@1.0) --with-static-linked-ext",
}

puts "# Good   : #{good.reverse.join " "}"
puts "# Install: #{install.reverse.join " "}"
puts "# Delete : #{delete.join " "}"
puts
puts "set -e"

puts
install.reverse_each do |ver|
  gem = "~/.rubies/ruby-#{ver}/bin/gem"

  puts "echo #{ver}"
  puts "ruby-install -c --no-reinstall --no-install-deps -j#{cpus} -s /tmp/ ruby #{ver} -- #{extra[ver]} &> /tmp/#{ver}.log && \\"
  puts "  #{gem} uninstall power_assert test-unit && \\"
  puts "  #{gem} install rubygems-cleanroom hoe hoe-seattlerb isolate minitest minitest-autotest minitest-sprint minitest-proveit benchmark-ips flay flog racc ruby2ruby && \\"
  puts "  chmod u-w $(#{gem} env home)/*"
  puts
end

delete.each do |ver|
  gem = "~/.rubies/ruby-#{ver}/bin/gem"
  puts "chmod u+w $(#{gem} env home)/*"
  puts "rm -rf ~/.rubies/ruby-#{ver}"
end
