#!/usr/bin/env ruby -ws

$B ||= false # bundler - keep bundler?!?

require "etc"
require "open-uri"
require "net/http" # avoid require issues in threads
require "net/https"

versions = %w[ 2.7 3.0 3.1 3.2 ] | ARGV

versions.unshift "2.6" # TODO: remove when minitest can drop it!

my_gems = %w[
             rubygems-cleanroom
             hoe
             hoe-seattlerb
             isolate
             minitest
             minitest-autotest
             minitest-sprint
             minitest-proveit
             benchmark-ips
             flay
             flog
             racc
             ruby2ruby
             rake-compiler
             pry
             pry-byebug
            ]

cpus = Etc.nprocessors

base_url = "https://cache.ruby-lang.org/pub/ruby"

gem_version = `gem search rubygems-update -v "~> 3.0"`[/\d+\.\d+\.\d+/]

class Array
  def human_sort
    sort_by { |item| item.to_s.split(/(\d+)/).map { |e| [e.to_i, e] } }
  end
end

versions = versions.map { |ver|
  Thread.new {
    URI
      .parse("#{base_url}/#{ver}/")
      .read
      .scan(/ruby-\d+\.\d+\.\d+[-\w.]*?.tar.gz/)
      .human_sort
      .last
      .delete_prefix("ruby-")
      .delete_suffix ".tar.gz"
  }
}.map(&:value).sort

rubies = File.expand_path "~/.rubies"
Dir.mkdir rubies unless File.directory? rubies

old_versions = Dir.chdir rubies do
  Dir["ruby-*"].map { |s| s.delete_prefix "ruby-" }.sort
end

good    = versions & old_versions
install = versions - old_versions
delete  = old_versions - versions

unless ARGV.empty? then
  version_re = Regexp.union ARGV

  good    = good.grep version_re
  install = install.grep version_re
  delete  = delete.grep version_re
end

# https://github.com/postmodern/ruby-install/issues/363#issuecomment-580699347
extra_args = {}
extra_args["2.3"] = "--with-openssl-dir=$(brew --prefix openssl@1.0) --with-static-linked-ext"

# https://github.com/postmodern/ruby-install/issues/399#issuecomment-829153466
extra_env = {}
extra_env["2.4"] = "CFLAGS=-Wno-error=implicit-function-declaration"
extra_env["2.5"] = extra_env["2.6"] = extra_env["2.4"]

latest = versions.last

puts "# Good   : #{good.reverse.join " "}"
puts "# Install: #{install.reverse.join " "}"
puts "# Delete : #{delete.join " "}"

puts
puts "set -exv"
puts

install.reverse_each do |ver|
  short_ver = ver[/^\d+\.\d+/]

  dir = "~/.rubies/ruby-#{ver}"
  gem = "#{dir}/bin/gem"

  puts "echo #{ver}"
  print "#{extra_env[short_ver]} " if extra_env[short_ver]
  puts "ruby-install -c --no-reinstall --no-install-deps -j#{cpus} -s /tmp/ ruby #{ver} -- #{extra_args[short_ver]} &> /tmp/#{ver}.log && \\"
  puts "  #{gem} update --system #{gem_version} -N && \\"
  puts "  #{gem} uninstall rubygems-update && \\"
  puts "  #{gem} uninstall power_assert test-unit && \\"
  puts "  #{gem} install #{my_gems.join " "} && \\"
  puts "  #{gem} clean && \\"
  puts "  chmod u-w $(#{gem} env home)/*"
  puts
end

delete.each do |ver|
  gem = "~/.rubies/ruby-#{ver}/bin/gem"
  puts "chmod u+w $(#{gem} env home)/*"
  puts "rm -rf ~/.rubies/ruby-#{ver}"
end

puts "ln -shF .rubies/ruby-#{latest}  ~/.rubies.current"
puts
