#!/usr/bin/bash
# skeleton - bare minimum shell for processing files

com=${0##*/}			# save command name

usage() {

  echo "Usage: $com version suntype"
  echo "Example: $com 50 9"
}

if [ $# -lt 2 ]; then	# check num of arguments
  usage
  exit 1
fi

version=$1
suntype=$2

case $suntype in
  9 )
      machine=RISC6000.AIX
      ;;
  8 )
      machine=Symmetry.Dynix
      ;;
  7 )
      machine=hppa.hpux
      #hppa.hpux_8
      #hppa.hpux_9
      ;;
  5 )
      machine=i386.ncr
      #i386.NCR
      ;;
  10 )
       machine=sparc.Solaris
       ;;
  4 )
      machine=sparc.SunOS4
      ;;
  * )
      echo "Unknown suntype"
      exit -1
esac

# Don't confuse $(command) with ${variable}
# if we are RUNNING on ncr, use cp.
if [ $(suntype) = "5" ]; then
	COPY=cp
else
	COPY=gcp
fi

echo Version=$version
echo Suntype=$suntype
echo Machine=$machine
echo Copy   =$COPY

if ( test  -d "fast$suntype" ); then
  chmod -R a+w fast$suntype
  command rm -rf fast$suntype
fi

echo $COPY -r /gcm/where/gemstone/$version/$machine/fast fast$suntype
$COPY -r /gcm/where/gemstone/$version/$machine/fast fast$suntype

if ( test  -d "slow$suntype" ); then
  chmod -R a+w slow$suntype
  command rm -rf slow$suntype
fi

echo $COPY -r /gcm/where/gemstone/$version/$machine/slow slow$suntype
$COPY -r /gcm/where/gemstone/$version/$machine/slow slow$suntype

if ( test  -d "noop$suntype" ); then
  chmod -R a+w noop$suntype
  command rm -rf noop$suntype
fi

echo $COPY -r /gcm/where/gemstone/$version/$machine/noop noop$suntype
$COPY -r /gcm/where/gemstone/$version/$machine/noop noop$suntype
