#! /usr/bin/bash

set -xv

thishost=`suntype`
thever="50"

if ( test  -d "fast$thishost" ); then
  chmod -R a+w fast$thishost
  command rm -rf fast$thishost
fi

if ( test  -d "slow$thishost" ); then
  chmod -R a+w slow$thishost
  command rm -rf slow$thishost
fi

if ( test  -d "noop$thishost" ); then
  chmod -R a+w noop$thishost
  command rm -rf noop$thishost
fi

if [ $thishost = "5" ]; then
	COPY=cp
else
	COPY=gcp
fi

$COPY -r /gcm/where/gemstone/$thever/$HOSTTYPE.$OSTYPE/fast fast$thishost
$COPY -r /gcm/where/gemstone/$thever/$HOSTTYPE.$OSTYPE/slow slow$thishost
$COPY -r /gcm/where/gemstone/$thever/$HOSTTYPE.$OSTYPE/noop noop$thishost
