#!/bin/sh -- # -*- perl -*-
eval 'exec perl -w -S $0 ${1+"$@"}'
  if 0;

use strict;
use HTML::Weblint;
use Carp ();

local $SIG{__WARN__} = \&Carp::cluck;
local $SIG{__DIE__} = \&Carp::cluck;

&HTML::Weblint::main(@ARGV);
