#! /usr/bin/bash
##################################################################
# 
# .bashrc
#
# Vers. Date	   Comment
# ----- ---------- -----------------------------------------------
# 1.1.0 1998-09-17 Amazon conversion
# 1.0.0 1996-10-04 Birthday
#
##################################################################

#set -xv

# For Reference:
#  Login shells:
#    On login (subject to the -noprofile option):
#          if /etc/profile exists, source it.
#
#          if ~/.bash_profile exists, source it,
#            else if ~/.bash_login exists, source it,
#              else if ~/.profile exists, source it.
#
#    On exit:
#          if ~/.bash_logout exists, source it.

umask 002	# no writes for others, otherwise fully open
set -P		# Turn off bash's relative pwd
set -u		# For a while, break when undefined variable is used.


CONFIG=$HOME/Bin/Config

export DOMAIN=$(hostname | perl -pe 's/.*\.([^\.]+\.[^\.]+)$/$1/;')
export HOSTNAME=$(hostname -s)

for f in $CONFIG/$DOMAIN $CONFIG/$HOSTNAME $CONFIG/environment; do
  if [ -f $f ] ; then
    . $f
  fi
done

case $- in
  
  # interactive shell
  *i*)
    
    ALIAS_FILE=$CONFIG/alias

    if [ -f $ALIAS_FILE ] ; then
      . $ALIAS_FILE
    fi
    ;;
  
  # not interactive
  *) 
    ;;
esac

    
