# -*- sh -*-

#set -xv

# For Reference:
#  Login shells:
#    On login (subject to the -noprofile option):
#          if /etc/profile exists, source it.
#
#          if ~/.bash_profile exists, source it,
#            else if ~/.bash_login exists, source it,
#              else if ~/.profile exists, source it.
#
#    On exit:
#          if ~/.bash_logout exists, source it.

umask 002	# no writes for others, otherwise fully open
set -P		# Turn off bash's relative pwd
set -u		# Break when undefined variable is used.

CONFIG=$HOME/Bin/Config

export DOMAIN=$(hostname | /usr/bin/perl -pe 's/^.*?([^\.]+\.[^\.]+)$/$1/;')
export HOSTNAME=$(hostname -s)

for f in $CONFIG/os/$(uname) $CONFIG/domain/$DOMAIN $CONFIG/host/$HOSTNAME $CONFIG/misc/environment; do
  if [ -f $f ] ; then
    . $f
  fi
done

if [[ $- == *i* ]]; then
  # interactive shell
  
  ALIAS_FILE=$CONFIG/misc/alias
  if [ -f $ALIAS_FILE ] ; then
    . $ALIAS_FILE
  fi
fi

if [ -d /usr/local/etc/bash_completion.d ]; then
    . /usr/local/etc/bash_completion.d/brew_bash_completion.sh
    . /usr/local/etc/bash_completion.d/hub.bash_completion.sh
fi
if [ -d /usr/local/git/contrib/completion ]; then
    . /usr/local/git/contrib/completion/git-completion.bash
fi
