#!/bin/bash

cmd=$(basename "$0")
dir=$(dirname  "$0")
cd "$dir" || exit 1
dir=$PWD
bindir=$(dirname "$dir")

echo "cmd is $cmd"
echo "dir is $dir"
echo "bin is $bindir"
cd "$bindir" || exit 1
rm -f ~/Bin; ln -s "$PWD" ~/Bin

cd "$dir" || exit 1

p=$(ruby -e 'puts Dir.pwd.delete_prefix("/tmp_mnt")')

for l in bash_login bash_profile profile; do
    rm -f -- $l
    ln -s bashrc $l
done

rm -f -- *~ emacs xinitrc

if [ ! -d ~/.ssh ]; then
    mkdir ~/.ssh
fi

rm -f ~/.ssh/config
ln misc/ssh_config ~/.ssh/config
chmod 700 ~/.ssh ~/.ssh/config
rm -f ~/.gitconfig
ln misc/gitconfig ~/.gitconfig

create_link() {
  p=$1
  f=$2

  if [ -L "$HOME/.$f" ]; then
    echo "Removing symlink ~/.$f"
    rm "$HOME/.$f"
  fi
  
  if [ -f "$HOME/.$f" ]; then
    echo "Moving ~/.$f to ~/.$f.old"
    mv -f "$HOME/.$f" "$HOME/.$f".old
  fi
  
  echo "Linking $p/$f from ~/.$f"
  ln -s "$p/$f" "$HOME/.$f"
}

for f in * ; do
  if [ -f "$f" ]; then
    if [ "$f" != "$cmd" ]; then
      create_link "$p" "$f"
    fi
  fi
done

create_link ~/Bin/elisp emacs.el
