#!/usr/bin/bash

cmd=$(basename $0)
dir=$(dirname  $0)

echo cmd is $cmd
echo dir is $dir

cd $dir

p=$(/usr/local/bin/perl -e 'use Cwd; $cwd = cwd(); $cwd =~ s|^/tmp_mnt||; print $cwd;')

for l in bash_login bash_profile profile; do
  if [ ! -e $l ]; then
    ln -s bashrc $l
  fi
done

for f in $( ls | grep -Ev "(\~|\#|CVS)" ) ; do

  if [ $f != $cmd ]; then

    if [ -L ~/.$f ]; then
      echo Removing symlink ~/.$f
      rm ~/.$f
    fi

    if [ -f ~/.$f ]; then
      echo Moving ~/.$f to ~/.$f.old
      mv ~/.$f ~/.$f.old
    fi

    echo Linking $p/$f from ~/.$f
    ln -s $p/$f ~/.$f

  fi

done
