#!/bin/bash

cmd=$(basename $0)
dir=$(dirname  $0)

echo cmd is $cmd
echo dir is $dir

cd $dir

p=$(perl -e 'use Cwd; $cwd = cwd(); $cwd =~ s|^/tmp_mnt||; print $cwd;')

for l in bash_login bash_profile profile; do
    rm -f $l
    ln -s bashrc $l
done

rm -f emacs
ln -s ../elisp/emacs.el emacs
rm -f xinitrc
ln -s xsession xinitrc

for f in $( ls | grep -Ev "(\~|\#)" ) ; do

  if [ -f $f ]; then
    if [ $f != $cmd ]; then
      
      if [ -L ~/.$f ]; then
	echo Removing symlink ~/.$f
	rm ~/.$f
      fi
      
      if [ -f ~/.$f ]; then
	echo Moving ~/.$f to ~/.$f.old
	mv ~/.$f ~/.$f.old
      fi
      
      echo Linking $p/$f from ~/.$f
      ln -s $p/$f ~/.$f
      
    fi
  fi

done
