#!/bin/bash

# if the following export creates an error, you need to 
# add execute permissions to the file. This is because
# of how xsession works. In otherwords, you are running
# is 'sh', not 'bash', if you aren't executable.

export PRINTER=bianchi
. ~/.bashrc

xrdb -load /toasters/toaster5/users/ryand/.Xresources
xmodmap ~/.xmodmap.dvorak
xscreensaver &

# Fix amazon.com's ncd xterm keyboards
# if [ $DOMAIN = "amazon.com" ]; then
#   xmodmap -e "keysym SunF37 = F12"
#   xmodmap -e "keysym SunF36 = F11"
# fi

# Exec Window Manager
#export LD_LIBRARY_PATH=/dept/snoc/arch/lib
export LD_LIBRARY_PATH=fvwm2/lib:${LD_LIBRARY_PATH-}
exec fvwm2
