#!/bin/bash
# -*- ksh -*-

# if the following export creates an error, you need to 
# add execute permissions to the file. This is because
# of how xsession works. In otherwords, you are running
# is 'sh', not 'bash', if you aren't executable.

cd ~

# just in case:
HOSTNAME=$(hostname -s)

LOG=~/.xinitrc.log
echo $(date): starting xinitrc on $HOSTNAME.$DOMAIN >> $LOG

xrdb -load ~/.Xresources
xmodmap -e "remove Lock = Caps_Lock"
xmodmap ~/.xmodmap.dvorak

if [ $DOMAIN = "amazon.com" ]; then
  export PRINTER=cow
  xhost +software-7 +website-build-1 +website-build-2 +mm-1-sun +remedy-1 +production-1 +production-2 +production-3 +software-batch-1 +remedy-1 +qa-tools-2 +qa-tools-3
  xscreensaver &
fi

if [ $DOMAIN = "zenspider.com" ]; then
  if [ $HOSTNAME = "itsy" ]; then
    xmodmap ~/.xmodmap.laptop
    xemacs -unmapped -f gnuserv-start &
  else
    xscreensaver &
  fi
fi

rxvt &

fvwm2

echo $(date): quitting xinitrc on $HOSTNAME.$DOMAIN >> $LOG
