#!/usr/bin/bash
# General Environment (ryand)

#set -xv

export P4CONFIG=.p4config
export HISTFILESIZE=10000 # total
export HISTSIZE=10000     # per session

############################################################
# Pathing:

export OLDPATH=$PATH
# shellcheck disable=SC2123
PATH=""
MYPATH=~/Bin:${HOSTPATH-}:${DOMAINPATH-}:${OSPATH-}

shopt -qs extglob
MYPATH=${MYPATH//+(:)/:}
shopt -qu extglob

oldIFS=$IFS
IFS=:
export PATH
for p in $MYPATH ; do
  if [ -d "$p" ]; then
    if [ -z "$PATH" ]; then
      PATH="$p"
    else
      PATH="$PATH:$p"
    fi
  else
    if [ -n "$p" ]; then
      echo "Path $p not found"
    fi
  fi
done
IFS=$oldIFS

export SAVEPATH=$PATH

shopt -s histappend
# PROMPT_COMMAND='history -a; history -n'

############################################################
# Other Global environment stuff:

# Set program datasize to be the max
ulimit -d "$(ulimit -Hd)"

case $- in
  
  # interactive shell
  *i*)
  export CDPATH=.:~/:~/Links:~/Work
  PS1='\! % '
  PS4='$0@$LINENO: '
  HISTCONTROL=ignoredups
  
  if [[ -n "${INSIDE_EMACS:-}" ]]; then
      export EDITOR="emacsclient"
  else
      # Regular shell
      export EDITOR="emacsclient -t"
  fi

  if test "${TERM-}" = "emacs" -o "${TERM-}" = "dumb" ; then
    export PAGER=cat

    if [ -n "${INSIDE_EMACS:-}" ]; then
        TERM=${TERM}-256color
    fi
  fi

  if [ -z "${PAGER-}" ]; then
      export PAGER=more
  fi
  
  # ESHELL is what emacs will run for a shell
  export ESHELL=/bin/bash
  
  ;;

  # not interactive
  *) 
    ;;
esac
