#!/usr/bin/env ruby

$-w = true
$q = ARGV.delete("-q")

versions    = %w[3.2 3.3 3.4 4.0]
active_ruby = ENV["CURRENT_RUBY"] || versions.last

class Array
  def human_sort
    sort_by { |item| item.to_s.split(/(\d+)/).map { |e| [e.to_i, e] } }
  end
end

puts "export MT_NO_ISOLATE=1"
puts

rb_dir = File.expand_path "~/.rubies"

unless File.directory? rb_dir then
  warn "echo no rubies found, bailing..."
  exit
end

versions.each do |ver|
  Dir.chdir "#{rb_dir}" do
    current = Dir["*#{ver}*"].human_sort.last
    short   = ver.delete "."
    var     = "RUBY#{short}"
    dir     = "RUBY#{short}DIR"

    unless current then
      warn "# ruby #{ver} not found, skipping." unless $q
      next
    end

    puts "export #{dir}=#{rb_dir}/#{current}"
    puts "export #{var}=$#{dir}/bin/ruby"
    puts "alias gem#{short}=$#{dir}/bin/gem"
    puts "alias irb#{short}=$#{dir}/bin/irb"
    puts "alias rake#{short}=$#{dir}/bin/rake"
    puts "alias ri#{short}=$#{dir}/bin/ri"
    puts "alias ruby#{short}=$#{dir}/bin/ruby"
    puts
  end
end

puts "if [ ! -e ~/.rubies.current ]; then"
puts "    ln -s .rubies/ruby-#{active_ruby}* .rubies.current"
puts "fi"

puts
puts "add_host_path ~/.rubies.current/bin"
