#!/usr/bin/env ruby -w

active_ruby = ENV["CURRENT_RUBY"] || "2.6"
versions    = %w[2.3 2.4 2.5 2.6 2.7]

class Array
  def human_sort
    sort_by { |item| item.to_s.split(/(\d+)/).map { |e| [e.to_i, e] } }
  end
end

puts "export MT_NO_ISOLATE=1"
puts

rb_dir = File.expand_path "~/.rubies"

versions.each do |ver|
  Dir.chdir "#{rb_dir}" do
    current = Dir["*#{ver}*"].human_sort.last
    short   = ver.delete "."
    var     = "RUBY#{short}"

    unless current then
      warn "# ruby #{ver} not found, skipping."
      next
    end

    puts "export #{var}=#{rb_dir}/#{current}"
    puts "alias gem#{short}=$#{var}/bin/gem"
    puts "alias irb#{short}=$#{var}/bin/irb"
    puts "alias rake#{short}=$#{var}/bin/rake"
    puts "alias ri#{short}=$#{var}/bin/ri"
    puts "alias ruby#{short}=$#{var}/bin/ruby"
    puts
  end
end

puts "if [ ! -e ~/.rubies.current ]; then"
puts "    ln -s .rubies/ruby-#{active_ruby}* .rubies.current"
puts "fi"

puts
puts "add_host_path ~/.rubies.current/bin"
